/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageAgenda;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Timer;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Mihai2.Popescu
 */
public class JFrame_Agenda extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Agenda
     */
    private List<Contact> contacte;

    private DefaultListModel model = new DefaultListModel();
    ContactFile contactFile = new ContactFile("db.txt");
    File registered = new File("registered.txt");
    private final String regCode = "1987";
    Random rand = new Random();
    static int randomNum;

    public JFrame_Agenda() throws InterruptedException {

        initComponents();
        List<Contact> aniversati = contactFile.getTodayAniversaryContacts("dupa Nume");
        if (aniversati.isEmpty()) {
            reloadList("Personalizata", "dupa Nume");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Aveti aniversati astazi in lista de contacte!");
//            aniversati.forEach((e) -> model.addElement(e));
            jComboBox_Filtrare.setSelectedIndex(3);
        }
        jList_Contacte.setModel(model);
        runBanner();
    }

    private void actualizeazaModel() {
        model.clear();
        contactFile.getAllContacts().forEach((e) -> model.addElement(e));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Contacte = new javax.swing.JList<>();
        jButton_Adauga = new javax.swing.JButton();
        jTextField_Nume = new javax.swing.JTextField();
        jTextField_Prenume = new javax.swing.JTextField();
        jTextFieldDataNasterii = new javax.swing.JTextField();
        jTextField_TEL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Banner = new javax.swing.JLabel();
        jLabel_Filtrare = new javax.swing.JLabel();
        jLabel_Ordonare = new javax.swing.JLabel();
        jComboBox_Ordonare = new javax.swing.JComboBox<>();
        jComboBox_Filtrare = new javax.swing.JComboBox<>();
        jTextField_Filtru = new javax.swing.JTextField();
        jButton_EDIT = new javax.swing.JButton();
        jButton_DELETE = new javax.swing.JButton();
        jButton_CLEAR = new javax.swing.JButton();
        jLabel_registermsg = new javax.swing.JLabel();
        jButton_Filter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_Export = new javax.swing.JMenuItem();
        jMenuItem_Import = new javax.swing.JMenuItem();
        jMenuItem_Iesire = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_About = new javax.swing.JMenuItem();
        jMenuItem_Register = new javax.swing.JMenuItem();

        jLabel4.setText("PRENUME");

        jMenuItem1.setText("jMenuItem1");

        GridBagLayout l_gl = new GridBagLayout();
        GridBagConstraints l_gbc = new GridBagConstraints();
        l_gbc.weightx = 1.0;
        l_gbc.gridwidth = GridBagConstraints.REMAINDER;
        l_gbc.anchor = GridBagConstraints.WEST;
        l_gbc.insets = new Insets(5, 10, 5, 5);
        l_gl.setConstraints(getContentPane(), l_gbc);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList_Contacte.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jList_Contacte.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ContacteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Contacte);

        getContentPane().setLayout(l_gl);
        getContentPane().add(jScrollPane1, l_gbc);

        jButton_Adauga.setText("Adauga");
        jButton_Adauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdaugaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Adauga, l_gbc);
        getContentPane().add(jTextField_Nume, l_gbc);
        getContentPane().add(jTextField_Prenume, l_gbc);
        getContentPane().add(jTextFieldDataNasterii, l_gbc);
        getContentPane().add(jTextField_TEL, l_gbc);

        jLabel2.setText("NUME");
        getContentPane().add(jLabel2, l_gbc);

        jLabel3.setText("PRENUME");
        getContentPane().add(jLabel3, l_gbc);

        jLabel5.setText("DATA N.");
        getContentPane().add(jLabel5, l_gbc);

        jLabel6.setText("TEL");
        getContentPane().add(jLabel6, l_gbc);

        jLabel_Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Banner.setText("BANNER LABEL");
        jLabel_Banner.setMaximumSize(new java.awt.Dimension(500, 80));
        jLabel_Banner.setMinimumSize(new java.awt.Dimension(500, 20));
        jLabel_Banner.setPreferredSize(new java.awt.Dimension(500, 80));
        getContentPane().add(jLabel_Banner, l_gbc);

        jLabel_Filtrare.setText("Filtrare: ");
        getContentPane().add(jLabel_Filtrare, l_gbc);

        jLabel_Ordonare.setText("Ordonare: ");
        getContentPane().add(jLabel_Ordonare, l_gbc);

        jComboBox_Ordonare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"dupa Nume", "dupa Prenume", "dupa Telefon"}));
        jComboBox_Ordonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OrdonareActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Ordonare, l_gbc);

        jComboBox_Filtrare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Personalizata", "numere de FIX", "numere de MOBIL", "aniversati astazi", "aniversati in curand"}));
        jComboBox_Filtrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FiltrareActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Filtrare, l_gbc);
        getContentPane().add(jTextField_Filtru, l_gbc);

        jButton_EDIT.setText("Editeaza");
        jButton_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EDITActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_EDIT, l_gbc);

        jButton_DELETE.setText("Sterge");
        jButton_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_DELETE, l_gbc);

        jButton_CLEAR.setText("Clear");
        jButton_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CLEAR, l_gbc);

        jLabel_registermsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_registermsg.setText("INREGISTRATI APLICATIA PENTRU A SCAPA DE RECLAME");
        getContentPane().add(jLabel_registermsg, l_gbc);

        jButton_Filter.setText("Filter");
        jButton_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FilterActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Filter, l_gbc);

        jMenu_File.setText("Fisier");
        jMenu_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_FileActionPerformed(evt);
            }
        });

        jMenuItem_Export.setText("Export");
        jMenuItem_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExportActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Export);

        jMenuItem_Import.setText("Import");
        jMenuItem_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ImportActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Import);

        jMenuItem_Iesire.setText("Iesire");
        jMenuItem_Iesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_IesireActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Iesire);

        jMenuBar1.add(jMenu_File);

        jMenu2.setText("Ajutor");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem_About.setText("Despre");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_About);

        jMenuItem_Register.setText("Inregistreaza");
        jMenuItem_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RegisterActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Register);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdaugaActionPerformed
        try {
            checkIfDuplicate();
            Contact c = new Contact(jTextField_Nume.getText(), jTextField_Prenume.getText(), jTextFieldDataNasterii.getText(), jTextField_TEL.getText());
            System.out.println(jTextFieldDataNasterii.getText());
            System.out.println(c.toString());
            contactFile.adauga(c);
            actualizeazaModel();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_AdaugaActionPerformed

    private boolean isRegistered() {
        return registered.exists();
    }

    private void runBanner() throws InterruptedException {
        File dir = new File(".");
        File[] bannereJpg = dir.listFiles(f -> f.getName().endsWith(".jpg"));

        TimerTask task;
        task = new TimerTask() {
            @Override
            public void run() {
                randomNum = rand.nextInt(4);
                ImageIcon poza = new ImageIcon(bannereJpg[randomNum].getAbsolutePath());
                jLabel_Banner.setIcon(poza);
                jLabel_Banner.setText("");
                if (isRegistered()) {
                    jLabel_Banner.setIcon(null);
//                    jLabel_Banner.setVisible(false);
//                    jLabel_Banner.setOpaque(true);
                    jLabel_Banner.setForeground(Color.BLACK);
                    jLabel_Banner.setText("REGISTERED");
                    jLabel_registermsg.setVisible(false);
//                    jLabel_Banner.setBackground(Color.CYAN);
                    this.cancel();
                }
            }
        };
        Timer timer = new Timer("Timer");
        timer.scheduleAtFixedRate(task, 0, 1000);
        Thread.sleep(1000);
    }


    private void checkIfDuplicate() {
        for (int i = 0; i <= jList_Contacte.getModel().getSize() - 1; i++) {
            Object value = jList_Contacte.getModel().getElementAt(i);
            String[] values = value.toString().split(",");

            if (jTextField_TEL.getText().equals(values[2]) &&
                    jTextField_Nume.getText().equals(values[0]) &&
                    jTextField_Prenume.getText().equals(values[1]) &&
                    jTextFieldDataNasterii.getText().equals(values[3])) {
                throw new UnsupportedOperationException("You already have this contact in your list!");
            }

        }
    }

    private boolean checkIfDuplicateAtImport(String row) {
        for (int i = 0; i <= jList_Contacte.getModel().getSize() - 1; i++) {
            Object value = jList_Contacte.getModel().getElementAt(i);
            String[] values = value.toString().split(",");
            String[] importedValues = row.toString().split(",");

            if (importedValues[2].equals(values[2]) &&
                    importedValues[0].equals(values[0]) &&
                    importedValues[1].equals(values[1])) {
                return true;
            }
        }
        return false;
    }

    private void jList_ContacteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ContacteValueChanged

        if (jList_Contacte.getSelectedIndex() >= 0) {
            Object value = jList_Contacte.getModel().getElementAt(jList_Contacte.getSelectedIndex());
            String[] values = value.toString().split(",");
            jTextField_Nume.setText(values[0]);
            jTextField_Prenume.setText(values[1]);
            jTextField_TEL.setText(values[2]);
            jTextFieldDataNasterii.setText(values[3]);
        }
    }//GEN-LAST:event_jList_ContacteValueChanged

    private void jComboBox_FiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FiltrareActionPerformed
        model.clear();
        reloadList(jComboBox_Filtrare.getSelectedItem().toString(), jComboBox_Ordonare.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_FiltrareActionPerformed

    private void jButton_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FilterActionPerformed
        model.clear();
        contactFile.getSomeContacts(jTextField_Filtru.getText(), jComboBox_Ordonare.getSelectedItem().toString()).forEach((e) -> model.addElement(e));
    }//GEN-LAST:event_jButton_FilterActionPerformed

    private void reloadList(String fil, String srt) {
        model.clear();
        jTextField_Filtru.setEnabled(false);
        jButton_Filter.setEnabled(false);
        clearAll();
        if (fil.equals("numere de MOBIL")) {
            contactFile.getMobileContacts(srt).forEach((e) -> model.addElement(e));
        } else if (fil.equals("numere de FIX")) {
            contactFile.getFixContacts(srt).forEach((e) -> model.addElement(e));
        } else if (fil.equals("aniversati astazi")) {
            contactFile.getTodayAniversaryContacts(srt).forEach((e) -> model.addElement(e));
        } else if (fil.equals("aniversati in curand")) {
            contactFile.getSoonToBeAniversaryContacts(srt).forEach((e) -> model.addElement(e));
        } else if (fil.equals("Personalizata")) {
            jTextField_Filtru.setEnabled(true);
            jButton_Filter.setEnabled(true);
            contactFile.getSomeContacts(jTextField_Filtru.getText(), srt).forEach((e) -> model.addElement(e));
        }
    }

    private void clearAll() {
        jTextField_Filtru.setText("");
        jTextField_Nume.setText("");
        jTextField_Prenume.setText("");
        jTextField_TEL.setText("");
        jTextFieldDataNasterii.setText("");
    }

    private void jButton_CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CLEARActionPerformed
        clearAll();
        jComboBox_Filtrare.setSelectedIndex(0);
        jComboBox_Ordonare.setSelectedIndex(0);
        reloadList(jComboBox_Filtrare.getSelectedItem().toString(), jComboBox_Ordonare.getSelectedItem().toString());
    }//GEN-LAST:event_jButton_CLEARActionPerformed

    private void jComboBox_OrdonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OrdonareActionPerformed
        model.clear();
        reloadList(jComboBox_Filtrare.getSelectedItem().toString(), jComboBox_Ordonare.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_OrdonareActionPerformed

    private void jButton_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EDITActionPerformed
        try {
            checkIfDuplicate();
            int selectedIndex = jList_Contacte.getSelectedIndex();
            Object value = jList_Contacte.getModel().getElementAt(selectedIndex);
            Contact c1 = new Contact(value.toString());
            Contact c2 = new Contact(jTextField_Nume.getText(), jTextField_Prenume.getText(), jTextFieldDataNasterii.getText(), jTextField_TEL.getText());
            contactFile.editeaza(c1, c2);
            actualizeazaModel();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_EDITActionPerformed

    private void jButton_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DELETEActionPerformed
        try {
            int selectedIndex = jList_Contacte.getSelectedIndex();
            Object value = jList_Contacte.getModel().getElementAt(selectedIndex);
            Contact c1 = new Contact(value.toString());
            contactFile.sterge(c1);
            actualizeazaModel();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_DELETEActionPerformed

    private void jMenu_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_FileActionPerformed

    }//GEN-LAST:event_jMenu_FileActionPerformed

    private void jMenuItem_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ImportActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        if (fileChooser.showOpenDialog(JFrame_Agenda.this) == JFileChooser.APPROVE_OPTION) {
            ContactFile imp = new ContactFile(fileChooser.getSelectedFile());
            System.out.println("A creat fisierul");
            List<Contact> lines = imp.importFromFile();
            System.out.println("A creat lista");
            System.out.println(lines.toString());
            lines.forEach((Contact impC) -> {
                try {
                    if (checkIfDuplicateAtImport(impC.toString()) == true) {
                        System.out.println("This is a duplicate contact");
                    } else {
                        contactFile.adauga(impC);
                    }
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
            });
        }
        actualizeazaModel();
    }//GEN-LAST:event_jMenuItem_ImportActionPerformed

    private void jMenuItem_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(JFrame_Agenda.this) == JFileChooser.APPROVE_OPTION) {
            actualizeazaModel();
            ContactFile exp = new ContactFile(fileChooser.getSelectedFile());

            if (fileChooser.getSelectedFile().toPath().toString().endsWith(".txt")) {
                for (int i = 0; i <= jList_Contacte.getModel().getSize() - 1; i++) {
                    Object value = jList_Contacte.getModel().getElementAt(i);
                    try {
                        exp.adauga((Contact) value);
                    } catch (IOException ex) {
                        Logger.getLogger(JFrame_Agenda.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Trebuie sa alegeti un fisier \".txt\"");
            }
        }
        actualizeazaModel();
    }//GEN-LAST:event_jMenuItem_ExportActionPerformed

    private void jMenuItem_IesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_IesireActionPerformed
        JFrame_Agenda.this.processWindowEvent(
                new WindowEvent(
                        JFrame_Agenda.this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jMenuItem_IesireActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RegisterActionPerformed
        String showInputDialog = JOptionPane.showInputDialog(rootPane, "Introduceti codul de activare");
        if (showInputDialog == null ? regCode == null : showInputDialog.equals(regCode)) {
            File file = new File("registered.txt");
            try {
                if (file.createNewFile()) jLabel_registermsg.setVisible(false);
                else JOptionPane.showMessageDialog(rootPane, "You have already registered the app!");
            } catch (IOException ex) {
                System.out.println(Arrays.toString(ex.getStackTrace()));
            }
        }
    }//GEN-LAST:event_jMenuItem_RegisterActionPerformed

    private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed
        Image img = Toolkit.getDefaultToolkit().getImage("mojo.jpg");
        ImageIcon imgicon = new ImageIcon(img);
        String s = "Aceasta este aplicatia dezvoltata de mine pentru proiectul\n"
                + "JavaProgrammer de la InfoAcademy.\n"
                + "Pentru inregistrarea aplicatiei introduceti codul(1987) in Register.\n"
                + "Aveti grija, nu se va petrece mare lucru!\n"
                + "\n"
                + "@Dev by Popescu Mihai, v1.0(prima si cea mai slaba)";
        JOptionPane.showMessageDialog(rootPane, s, "JustAnApp", JOptionPane.PLAIN_MESSAGE, imgicon);
    }//GEN-LAST:event_jMenuItem_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        SplashScreen sp = new SplashScreen();

        java.awt.EventQueue.invokeLater(() -> {
            try {
                JFrame_Agenda frame = new JFrame_Agenda();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Agenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Adauga;
    private javax.swing.JButton jButton_CLEAR;
    private javax.swing.JButton jButton_DELETE;
    private javax.swing.JButton jButton_EDIT;
    private javax.swing.JButton jButton_Filter;
    private javax.swing.JComboBox<String> jComboBox_Filtrare;
    private javax.swing.JComboBox<String> jComboBox_Ordonare;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Banner;
    private javax.swing.JLabel jLabel_Filtrare;
    private javax.swing.JLabel jLabel_Ordonare;
    private javax.swing.JLabel jLabel_registermsg;
    private javax.swing.JList<String> jList_Contacte;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenuItem jMenuItem_Export;
    private javax.swing.JMenuItem jMenuItem_Iesire;
    private javax.swing.JMenuItem jMenuItem_Import;
    private javax.swing.JMenuItem jMenuItem_Register;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDataNasterii;
    private javax.swing.JTextField jTextField_Filtru;
    private javax.swing.JTextField jTextField_Nume;
    private javax.swing.JTextField jTextField_Prenume;
    private javax.swing.JTextField jTextField_TEL;
    // End of variables declaration//GEN-END:variables
}
